### ISSUE TITLE
Tombstone page

### ISSUE THREAD

**Issue by mfenner** [datacite/freya#1]
As a researcher, I want to see a tombstone page if a dataset is no longer available, so that I can at least get basic information about that dataset.

**Comment by mfenner** [comment]
Comment from @mwittin in https://github.com/datacite/datacite/issues/226#issuecomment-348559846: 

Either as a part of this issue or for a new one, clients should have the option of displaying citation metadata of a tombstoned DOI with reason for why DOI intentionally does not to resolve to a resource, e.g., the resource was deaccessioned. DataCite should provide this as a part of its platform to support eventual failing of clients/members. Also some client's systems do not provide this capability. This functionality is used by current EZID subscribers, so it may be considered important for some for migration as potential new members.

**Comment by lnielsen** [comment]
👍 I think it would be useful if the tombstone landing pages were a feature in DataCite. The use cases I see for it is 1) a repository is closed down, so it cannot hosts their own tombstone pages 2) all DataCite tombstone pages are identical and some minimal identical metadata.

**Comment by mfenner** [comment]
Related: datacite/cheetoh#8.
