### ISSUE TITLE
Link checking - Gather test set of links

### ISSUE THREAD

**Issue by richardhallett** [datacite/freya#17]
To help understand the types of landing pages and the various ways a possible "error" can return, it would be good to compile a list of example links.

**Comment by mfenner** [comment]
Maybe we call this a **Test Set** that includes easy ones and edge cases we are aware of. The **Test Set** could simply be a list of URLs in a text file or sitemap.xml.

**Comment by richardhallett** [comment]
Added a CSV file with some basic random samples of different landing pages I've found:
https://github.com/datacite/freya/blob/master/sample_landing_pages.csv
