### ISSUE TITLE
Store pidcheck results in mds database

### ISSUE THREAD

**Issue by mfenner** [datacite/freya#21]
### DEV NOTES

* decide on information that needs to be stored. 
* push to existing API endpoint

The MDS database currently stores this information:

* last_landing_page
* last_landing_page_content_type
* last_landing_page_status
* last_landing_page_status_check (datetime last checked)

The API endpoint is at https://app.datacite.org/dois.

**Comment by richardhallett** [comment]
This is about incorporating the best practices proposed by Freya for link checking, however it is DataCite specific and so moving over to our internal issues.
