### ISSUE TITLE
Expanding bi-directional links in HEP

### ISSUE THREAD

**Issue by ArtemisLav** [datacite/freya#28]
As a High-Energy Physics researcher, I want to see bi-directional links between CERN Analysis Preservation records and INSPIRE or HEPData records for cases where a physics analysis on CAP has resulted in a published resource.

**Comment by vasilyb** [comment]
Bi-directional links can be of a common interest (not only in High Energy Physics). One generic case (of many possible) could be having data cited by a research paper; it will be nice to always have a back link from data to the paper. Some data repositories add such links but not systematically, or only to one "representative" publication (that tells "the best" story about the dataset), but the question is how to build such back links to all publications that cite the data.

**Comment by mfenner** [comment]
This issue was moved to https://www.pidforum.org/t/expanding-bi-directional-links-in-hep/105
