### ISSUE TITLE
User stories for cultural artefact PIDs

### ISSUE THREAD

**Issue by RachaelKotarski** [datacite/freya#36]
“As a museum curator, I want to track the history of the placement of an item including where exactly it has been displayed and in which exhibitions (including loans), where it has been stored, and the atmospheric conditions of those storage locations over time.”
		OR
“As a museum curator, I want access to accurate data about paint samples taken from artworks over time to assist me in their conservation. I want this information to be publicly accessible.”

**Comment by ChrisVFerg** [comment]
Sample PID? 
Requires info about [geographical] location (in metadata?)

**Comment by mfenner** [comment]
This issue was moved to https://www.pidforum.org/t/user-stories-for-cultural-artefact-pids/108
