### ISSUE TITLE
Identifying historical or mythical personages

### ISSUE THREAD

**Issue by BlemonBL** [datacite/freya#42]
“As an historian of ancient civilisations, I need a means of identifying precisely which version of a fictional or mythical personage I am writing about, particularly when the existence of that individual and/or their surrounding circumstances are contested.”

**Comment by BlemonBL** [comment]
A note to acknowledge that PIDs for historical people, historical geographies and timeframes are unlikely to fit with current formats or approaches to metadata. They will likely rely upon further collaborative projects that can collate definitions of people, places and eras and can handle multiple versions of the same subject.

**Comment by mfenner** [comment]
This issue was moved to https://www.pidforum.org/t/identifying-historical-or-mythical-personages/90
