### ISSUE TITLE
Identifying historical timeframes

### ISSUE THREAD

**Issue by BlemonBL** [datacite/freya#46]
“As an historian, I need to identify which definition of a particular historical timeframe I have adopted (e.g. the Elizabethan era) in my work, particularly where the dates and definitions of those eras are contested.”

**Comment by BlemonBL** [comment]
A note to acknowledge that PIDs for historical people, historical geographies and timeframes are unlikely to fit with current formats or approaches to metadata. They will likely rely upon further collaborative projects that can collate definitions of people, places and eras and can handle multiple versions of the same subject.

**Comment by ChrisVFerg** [comment]
Don't kill me - I've added a 'sample' tag here for the purposes of D3.2. Also 'historical timeframes' were classified (rightly/wrongly) as time 'samples' for study in D3.1

**Comment by mfenner** [comment]
This issue was moved to https://www.pidforum.org/t/identifying-historical-timeframes/96
