### ISSUE TITLE
Making easier to cite resources

### ISSUE THREAD

**Issue by ArtemisLav** [datacite/freya#47]
As a HEP researcher, I want it to be easier to add correct citations to data and code in a specific state in order to give credit and to ensure the transparency of my analysis.

**Comment by mfenner** [comment]
Do you mean being able to cite specific versions of data and code?

**Comment by ArtemisLav** [comment]
Sure, that too, but this was more about the fact that researchers don't really get easy access to instructions on how to cite resources properly, i.e. the "cite as" used in many repositories.

**Comment by mfenner** [comment]
Thanks.

**Comment by mfenner** [comment]
This issue was moved to https://www.pidforum.org/t/making-easier-to-cite-resources/119
