### ISSUE TITLE
Link Check - Presentation

### ISSUE THREAD

**Issue by richardhallett** [datacite/freya#5]
We need to present the results of link checking in order for action to be taken.

## Questions

* Do we need to provide in a machine readable format?
* Do we need to provide monthly reports in a format that can be passed to clients, i.e. email?
* How often do people need to know that a PID is unhealthy?

**Comment by mfenner** [comment]
The DataCite Services Steering Group has discussed link checking earlier in 2017. There was consensus that link checker reports should not be public, at least until we enough confidence in the reporting.

**Comment by richardhallett** [comment]
Based upon discussions with the Freya WG, at this time it's complicated to present the result data out and instead PID Providers should focus on taking the data and using it internally to help identify potential issues.
