### ISSUE TITLE
Records enrichment in institutional repositories

### ISSUE THREAD

**Issue by vasilyb** [datacite/freya#72]
As an owner or an operator of an institutional publications or data repository I am interested in records enrichment with links to identifiable chemical substances, biological objects, species, geolocations etc. that are mentioned in the record title, abstract, or in the associated full text/description. I would like to focus on text mining techniques first with possible extensions for the automated image or data characterization.

**Comment by mfenner** [comment]
Is there a role for PIDs in this?

**Comment by vasilyb** [comment]
Sure there is a role for PIDs in this, as there are mature services for chemical and biological substances. On one hand, we may say "this is too much for FREYA"; on the other hand, the quality of these services may be so good that they are "low-hanging fruits" for integration or for harvesting from them. Also services is not the only kind of FREYA outcomes (although we have to do our best to deliver them). FREYA can also deliver recommendations illustrated by the actually built graphs. From services perspective, such FREYA outcomes can be considered well-illustrated requirements for future services - perhaps in view of future projects that can actually deliver them.

**Comment by vasilyb** [comment]
This issue is not stale as it is closely related to the joint works of STFC and EBI planned and outlined in D3.2

**Comment by daslerr** [comment]
don't close
