### ISSUE TITLE
Repositories who expose schema.org metadata on landing pages

### ISSUE THREAD

**Issue by mfenner** [datacite/freya#8]
What are FREYA partners doing? What are other data repositories doing. Please add repos in comments or directly to the CSV file: https://github.com/datacite/freya/blob/master/schema_org.csv

**Comment by djbordelon** [comment]
Hello there,
at European Southern Observatory, we aren't yet minting DOIs for datasets--will begin sometime this year--but we are using DataCite DOIs for publications, and we already embed schema.org JSON-LD in landing pages for these. We will do the same once we start minting dataset DOIs.

Example: https://doi.org/10.18727/0722-6691/5056

edit: I should perhaps add that in the JSON-LD, we surface periodical information (volume, page) that is not structured in the DataCite Metadata Schema.

**Comment by mfenner** [comment]
Thanks. At this point in time the focus is on datasets, but good to know that you will do the same for datasets when you get there.

**Comment by efgramsbergen** [comment]
We, at 4TU Centre for Research Data, just implemented json-ld. Example: https://doi.org/10.4121/uuid:a9785e91-e478-422e-a3d6-783a0ca5fa03 . Please note that we use a @list for multiple authors, because the order of authors is often considered important.

**Comment by TomDemeranville** [comment]
Happy to see ORCID in your schema.org @efgramsbergen !  We're going to put schema.org in place at the ORCID end sometime soon.

**Comment by par4dise** [comment]
Is it dedicated to repositories? Or a landing page for a single dataset also can be added?

**Comment by mfenner** [comment]
This is really about repositories, in the broadest sense. The list would get too long otherwise...

**Comment by par4dise** [comment]
Ok no problem, you're right. Thanks for your answer.
