### ISSUE TITLE
Open Access versions of published articles

### ISSUE THREAD

**Issue by TomDemeranville** [datacite/freya#84]
As a researcher/administrator I would like to discover the open access versions of my published articles so that I can comply with funding reporting.

**Comment by TomDemeranville** [comment]
i.e. given a DOI, tell me all the OA versions of the content that DOI (and their DOIs/PIDs)

**Comment by mfenner** [comment]
This sounds like unpaywall to me: https://unpaywall.org/. Or is this different?
