### ISSUE TITLE
Define Core Metadata

### ISSUE THREAD

**Issue by mfenner** [datacite/freya#9]
What are the required core metadata for FREYA PIDs?

We defined required citation metadata in https://doi.org/10.1101/097196:

* identifier
* name
* author
* publisher
* datePublished
* version
* type

**Comment by mfenner** [comment]
We might need other metadata besides citation metadata, e.g. checksums.

**Comment by sarala** [comment]
Minimum dataset metadata from Bioschemas effort - http://bioschemas.org/specifications/Dataset/specification/

- description
- identifier
- keywords	
- name
- url
 
Recommended properties

- citation
- creator
- distribution	
- includedInDataCatalog
- license
- measurementTechnique
- variableMeasured

**Comment by mfenner** [comment]
Thanks. Looks like `description` and `keywords` are in bioschemas, but not in DCIP. And `author` and `publisher` are optional instead of required. What about `datePublished`, `version` and `type`?

**Comment by mfenner** [comment]
I have updated the DCIP list using schema.org properties.

**Comment by mfenner** [comment]
don't close.
