### ISSUE TITLE
Including heritage literature in repositories

### ISSUE THREAD

**Issue by ChrisVFerg** [datacite/freya#90]
As the Manager of the Biodiversity Heritage Library (BHL) in Australia, I want to see DOIs applied to the world’s biodiversity heritage literature so that this literature can be part of the great linked network of scholarly research (the DOI system).

... I also want to work with the global DOI community to ensure that the DOIs for out-of-copyright literature are #OpenAccess (& do not resolve to versions behind paywalls)

Ambassador Webinar 16 Oct 2018

**Comment by mfenner** [comment]
This issue was moved to https://www.pidforum.org/t/including-heritage-literature-in-repositories/56
