### ISSUE TITLE
Tracing/relocating misplaced cultural artefacts

### ISSUE THREAD

**Issue by ChrisVFerg** [datacite/freya#91]
Here's an interesting user story was collected at the DI4R workshop from Olivia Kaiser Vienna University Library olivia.kaiser@univie.ac.at 

As a provenance researcher for Nazi-looted books, I wish for PIDs for stamps, exlibris, autographs, place of looting, place of storage. Could help to find objects of a former owner/collection which was torn apart by Nazi looting.

**Comment by mfenner** [comment]
This issue was moved to https://www.pidforum.org/t/tracing-relocating-misplaced-cultural-artefacts/53
